### ISSUE TITLE
+1 for Redux 

### ISSUE THREAD

**Issue by stonebraker** [ZacharyKlein/grails-react-starter#2]
Having an example app using Redux in Grails would be great. I'll be taking a stab at implementing react-router.

As an aside, I found your [Using React with Grails](https://www.ociweb.com/resources/publications/sett/june-2016-using-react-with-grails/) blog post very helpful. Thanks for that.

**Comment by ZacharyKlein** [comment]
Thanks @stonebraker - sorry I just saw this now! I think Redux is an excellent library, I'm not sure if there's anything Grails specific about implementing it. Also, the React profile for Grails is no available: https://github.com/grails-profiles/react
